name: Macosko_Rsf
channels:
  - conda-forge
  - defaults
dependencies:
  - mamba
  - r-ape=5.6_2
  - r-base=4.2.2
  - r-data.tree=1.0.0
  - r-dbscan=1.1_11
  - r-devtools=2.4.5
  - r-doparallel=1.0.17
  - r-essentials=4.2
  - r-fastmatch=1.1_3
  - r-furrr=0.3.1
  - r-ggextra=0.10.0
  - r-ggpubr=0.5.0
  - r-ggrastr=1.0.1
  - r-hdf5r=1.3.7
  - r-hues=0.2.0
  - r-lidr=4.0.2
  - r-magrittr=2.0.3
  - r-pals=1.7
  - r-pheatmap=1.0.12
  - r-qs=0.25.4
  - r-quadprog=1.5_8
  - r-rfast=2.0.6
  - r-rmapshaper=0.4.6
  - r-seurat=4.3.0
  - r-sf=1.0_7
  - r-tidyr=1.2.1
  - r-rdist=0.0.5
  - r-paletteer=1.6.0
