name: atlas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - nodejs
  # cloud
  - gcsfs
  - google-auth
  - google-cloud-secret-manager
  # data
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pynndescent
  - pytables
  - scipy
  - sparse
  - umap-learn
  - zarr
  # dask
  - coiled
  - dask
  - dask-labextension
  - dask-ml
  # visualization
  - bokeh
  - datashader
  - holoviews
  - jupyter_bokeh
  - jupyterlab_pyviz
  - matplotlib
