name: atlas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyterlab
  - nodejs
  - click
  # cloud
  - gcsfs
  - google-api-python-client
  - google-auth
  - google-cloud-secret-manager
  # data
  - h5py
  - leidenalg
  - numba
  - numpy
  - openpyxl
  - pandas
  - pyarrow
  - pynndescent
  - pyyaml
  - scipy
  - sparse
  - umap-learn
  - zarr
  # dask
  - dask
  - dask-labextension
  - dask-ml
  # visualization
  - bokeh
  - jupyter_bokeh
  - matplotlib
  - pip:
      - -e .
