name: atlas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - click
  - dask
  - dask-ml
  - gcsfs
  - google-api-python-client
  - google-auth
  - leidenalg
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyarrow
  - pynndescent
  - python-igraph
  - pyyaml
  - scipy
  - sparse
  - zarr
  - pip:
      - protobuf==3.20.1
      - hail
      - dill
      - -e .
