FROM mambaorg/micromamba:0.24.0

COPY --chown=$MAMBA_USER:$MAMBA_USER . /brain-atlas

RUN cd /brain-atlas \
       && micromamba install -n base -y -f hail_environment.yml \
       && micromamba clean -afy \
       && /opt/conda/bin/pip install . --no-deps

RUN rm -rf /opt/conda/conda-meta && \
  rm -rf /opt/conda/include && \
  rm /opt/conda/lib/libpython3.7m.so.1.0 && \
  find /opt/conda -name '__pycache__' -type d -exec rm -rf '{}' '+' && \
  rm -rf /opt/conda/lib/python3.7/site-packages/pip /opt/conda/lib/python3.7/idlelib /opt/conda/lib/python3.7/ensurepip \
    /opt/conda/bin/sqlite3 \
    /opt/conda/bin/openssl && \
  find /opt/conda -name 'tests' -type d -print0 | xargs -0 rm -r && \
  find /opt/conda -name '*.a' -type f -delete

ARG MAMBA_DOCKERFILE_ACTIVATE=1

# hail batch fails internally if not run as root, seems to work fine with conda
USER root

# Useful commands
#     sudo docker build -t atlas .
#     sudo docker run --rm -ti atlas
#     sudo docker build --squash -t gcr.io/mouse-brain-atlas/jonahatlas .
#     sudo docker push gcr.io/mouse-brain-atlas/jonahatlas
