name: atlas
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - click
  - dask-core
  - distributed
  - gcsfs
  - numba
  - numpy
  - scipy
  - zarr
  - pip:
      - protobuf==3.20.1
      - dill
